/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkIndexRouteImport } from './routes/work.index'
import { Route as SigninIndexRouteImport } from './routes/signin.index'
import { Route as OpsIndexRouteImport } from './routes/ops.index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as WorkSupervisorRouteImport } from './routes/work.supervisor'
import { Route as WorkShiftRouteImport } from './routes/work.shift'
import { Route as WorkHistoryRouteImport } from './routes/work.history'
import { Route as WorkAssessRouteImport } from './routes/work.assess'
import { Route as SigninSentRouteImport } from './routes/signin.sent'
import { Route as SigninExpiredRouteImport } from './routes/signin.expired'
import { Route as OpsSystemRouteImport } from './routes/ops.system'
import { Route as OpsShiftsRouteImport } from './routes/ops.shifts'
import { Route as OpsServicesRouteImport } from './routes/ops.services'
import { Route as OpsOversightRouteImport } from './routes/ops.oversight'
import { Route as OpsMdasRouteImport } from './routes/ops.mdas'
import { Route as OpsKeysRouteImport } from './routes/ops.keys'
import { Route as OpsIntegratorsRouteImport } from './routes/ops.integrators'
import { Route as OpsAuditRouteImport } from './routes/ops.audit'
import { Route as OpsAdaptersRouteImport } from './routes/ops.adapters'
import { Route as DocsWebhooksRouteImport } from './routes/docs.webhooks'
import { Route as DocsSecurityRouteImport } from './routes/docs.security'
import { Route as DocsSdksRouteImport } from './routes/docs.sdks'
import { Route as DocsQuickStartRouteImport } from './routes/docs.quick-start'
import { Route as DocsExplorerRouteImport } from './routes/docs.explorer'
import { Route as DocsCookbookRouteImport } from './routes/docs.cookbook'
import { Route as DocsApiStandardsRouteImport } from './routes/docs.api-standards'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardLogsRouteImport } from './routes/dashboard.logs'
import { Route as DashboardKeysRouteImport } from './routes/dashboard.keys'
import { Route as DashboardBillingRouteImport } from './routes/dashboard.billing'
import { Route as WorkCollectIdRouteImport } from './routes/work.collect.$id'
import { Route as DocsCatalogueServicesRouteImport } from './routes/docs.catalogue.services'
import { Route as DocsCatalogueAgenciesRouteImport } from './routes/docs.catalogue.agencies'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkRoute,
} as any)
const SigninIndexRoute = SigninIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SigninRoute,
} as any)
const OpsIndexRoute = OpsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpsRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const WorkSupervisorRoute = WorkSupervisorRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => WorkRoute,
} as any)
const WorkShiftRoute = WorkShiftRouteImport.update({
  id: '/shift',
  path: '/shift',
  getParentRoute: () => WorkRoute,
} as any)
const WorkHistoryRoute = WorkHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => WorkRoute,
} as any)
const WorkAssessRoute = WorkAssessRouteImport.update({
  id: '/assess',
  path: '/assess',
  getParentRoute: () => WorkRoute,
} as any)
const SigninSentRoute = SigninSentRouteImport.update({
  id: '/sent',
  path: '/sent',
  getParentRoute: () => SigninRoute,
} as any)
const SigninExpiredRoute = SigninExpiredRouteImport.update({
  id: '/expired',
  path: '/expired',
  getParentRoute: () => SigninRoute,
} as any)
const OpsSystemRoute = OpsSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => OpsRoute,
} as any)
const OpsShiftsRoute = OpsShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => OpsRoute,
} as any)
const OpsServicesRoute = OpsServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => OpsRoute,
} as any)
const OpsOversightRoute = OpsOversightRouteImport.update({
  id: '/oversight',
  path: '/oversight',
  getParentRoute: () => OpsRoute,
} as any)
const OpsMdasRoute = OpsMdasRouteImport.update({
  id: '/mdas',
  path: '/mdas',
  getParentRoute: () => OpsRoute,
} as any)
const OpsKeysRoute = OpsKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => OpsRoute,
} as any)
const OpsIntegratorsRoute = OpsIntegratorsRouteImport.update({
  id: '/integrators',
  path: '/integrators',
  getParentRoute: () => OpsRoute,
} as any)
const OpsAuditRoute = OpsAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => OpsRoute,
} as any)
const OpsAdaptersRoute = OpsAdaptersRouteImport.update({
  id: '/adapters',
  path: '/adapters',
  getParentRoute: () => OpsRoute,
} as any)
const DocsWebhooksRoute = DocsWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSecurityRoute = DocsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSdksRoute = DocsSdksRouteImport.update({
  id: '/sdks',
  path: '/sdks',
  getParentRoute: () => DocsRoute,
} as any)
const DocsQuickStartRoute = DocsQuickStartRouteImport.update({
  id: '/quick-start',
  path: '/quick-start',
  getParentRoute: () => DocsRoute,
} as any)
const DocsExplorerRoute = DocsExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCookbookRoute = DocsCookbookRouteImport.update({
  id: '/cookbook',
  path: '/cookbook',
  getParentRoute: () => DocsRoute,
} as any)
const DocsApiStandardsRoute = DocsApiStandardsRouteImport.update({
  id: '/api-standards',
  path: '/api-standards',
  getParentRoute: () => DocsRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLogsRoute = DashboardLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKeysRoute = DashboardKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const WorkCollectIdRoute = WorkCollectIdRouteImport.update({
  id: '/collect/$id',
  path: '/collect/$id',
  getParentRoute: () => WorkRoute,
} as any)
const DocsCatalogueServicesRoute = DocsCatalogueServicesRouteImport.update({
  id: '/catalogue/services',
  path: '/catalogue/services',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCatalogueAgenciesRoute = DocsCatalogueAgenciesRouteImport.update({
  id: '/catalogue/agencies',
  path: '/catalogue/agencies',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/ops': typeof OpsRouteWithChildren
  '/signin': typeof SigninRouteWithChildren
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work': typeof WorkRouteWithChildren
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/keys': typeof DashboardKeysRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/docs/api-standards': typeof DocsApiStandardsRoute
  '/docs/cookbook': typeof DocsCookbookRoute
  '/docs/explorer': typeof DocsExplorerRoute
  '/docs/quick-start': typeof DocsQuickStartRoute
  '/docs/sdks': typeof DocsSdksRoute
  '/docs/security': typeof DocsSecurityRoute
  '/docs/webhooks': typeof DocsWebhooksRoute
  '/ops/adapters': typeof OpsAdaptersRoute
  '/ops/audit': typeof OpsAuditRoute
  '/ops/integrators': typeof OpsIntegratorsRoute
  '/ops/keys': typeof OpsKeysRoute
  '/ops/mdas': typeof OpsMdasRoute
  '/ops/oversight': typeof OpsOversightRoute
  '/ops/services': typeof OpsServicesRoute
  '/ops/shifts': typeof OpsShiftsRoute
  '/ops/system': typeof OpsSystemRoute
  '/signin/expired': typeof SigninExpiredRoute
  '/signin/sent': typeof SigninSentRoute
  '/work/assess': typeof WorkAssessRoute
  '/work/history': typeof WorkHistoryRoute
  '/work/shift': typeof WorkShiftRoute
  '/work/supervisor': typeof WorkSupervisorRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/ops/': typeof OpsIndexRoute
  '/signin/': typeof SigninIndexRoute
  '/work/': typeof WorkIndexRoute
  '/docs/catalogue/agencies': typeof DocsCatalogueAgenciesRoute
  '/docs/catalogue/services': typeof DocsCatalogueServicesRoute
  '/work/collect/$id': typeof WorkCollectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/keys': typeof DashboardKeysRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/docs/api-standards': typeof DocsApiStandardsRoute
  '/docs/cookbook': typeof DocsCookbookRoute
  '/docs/explorer': typeof DocsExplorerRoute
  '/docs/quick-start': typeof DocsQuickStartRoute
  '/docs/sdks': typeof DocsSdksRoute
  '/docs/security': typeof DocsSecurityRoute
  '/docs/webhooks': typeof DocsWebhooksRoute
  '/ops/adapters': typeof OpsAdaptersRoute
  '/ops/audit': typeof OpsAuditRoute
  '/ops/integrators': typeof OpsIntegratorsRoute
  '/ops/keys': typeof OpsKeysRoute
  '/ops/mdas': typeof OpsMdasRoute
  '/ops/oversight': typeof OpsOversightRoute
  '/ops/services': typeof OpsServicesRoute
  '/ops/shifts': typeof OpsShiftsRoute
  '/ops/system': typeof OpsSystemRoute
  '/signin/expired': typeof SigninExpiredRoute
  '/signin/sent': typeof SigninSentRoute
  '/work/assess': typeof WorkAssessRoute
  '/work/history': typeof WorkHistoryRoute
  '/work/shift': typeof WorkShiftRoute
  '/work/supervisor': typeof WorkSupervisorRoute
  '/dashboard': typeof DashboardIndexRoute
  '/docs': typeof DocsIndexRoute
  '/ops': typeof OpsIndexRoute
  '/signin': typeof SigninIndexRoute
  '/work': typeof WorkIndexRoute
  '/docs/catalogue/agencies': typeof DocsCatalogueAgenciesRoute
  '/docs/catalogue/services': typeof DocsCatalogueServicesRoute
  '/work/collect/$id': typeof WorkCollectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/ops': typeof OpsRouteWithChildren
  '/signin': typeof SigninRouteWithChildren
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work': typeof WorkRouteWithChildren
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/keys': typeof DashboardKeysRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/docs/api-standards': typeof DocsApiStandardsRoute
  '/docs/cookbook': typeof DocsCookbookRoute
  '/docs/explorer': typeof DocsExplorerRoute
  '/docs/quick-start': typeof DocsQuickStartRoute
  '/docs/sdks': typeof DocsSdksRoute
  '/docs/security': typeof DocsSecurityRoute
  '/docs/webhooks': typeof DocsWebhooksRoute
  '/ops/adapters': typeof OpsAdaptersRoute
  '/ops/audit': typeof OpsAuditRoute
  '/ops/integrators': typeof OpsIntegratorsRoute
  '/ops/keys': typeof OpsKeysRoute
  '/ops/mdas': typeof OpsMdasRoute
  '/ops/oversight': typeof OpsOversightRoute
  '/ops/services': typeof OpsServicesRoute
  '/ops/shifts': typeof OpsShiftsRoute
  '/ops/system': typeof OpsSystemRoute
  '/signin/expired': typeof SigninExpiredRoute
  '/signin/sent': typeof SigninSentRoute
  '/work/assess': typeof WorkAssessRoute
  '/work/history': typeof WorkHistoryRoute
  '/work/shift': typeof WorkShiftRoute
  '/work/supervisor': typeof WorkSupervisorRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/ops/': typeof OpsIndexRoute
  '/signin/': typeof SigninIndexRoute
  '/work/': typeof WorkIndexRoute
  '/docs/catalogue/agencies': typeof DocsCatalogueAgenciesRoute
  '/docs/catalogue/services': typeof DocsCatalogueServicesRoute
  '/work/collect/$id': typeof WorkCollectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/docs'
    | '/ops'
    | '/signin'
    | '/signup'
    | '/sitemap.xml'
    | '/work'
    | '/dashboard/billing'
    | '/dashboard/keys'
    | '/dashboard/logs'
    | '/dashboard/settings'
    | '/docs/api-standards'
    | '/docs/cookbook'
    | '/docs/explorer'
    | '/docs/quick-start'
    | '/docs/sdks'
    | '/docs/security'
    | '/docs/webhooks'
    | '/ops/adapters'
    | '/ops/audit'
    | '/ops/integrators'
    | '/ops/keys'
    | '/ops/mdas'
    | '/ops/oversight'
    | '/ops/services'
    | '/ops/shifts'
    | '/ops/system'
    | '/signin/expired'
    | '/signin/sent'
    | '/work/assess'
    | '/work/history'
    | '/work/shift'
    | '/work/supervisor'
    | '/dashboard/'
    | '/docs/'
    | '/ops/'
    | '/signin/'
    | '/work/'
    | '/docs/catalogue/agencies'
    | '/docs/catalogue/services'
    | '/work/collect/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signup'
    | '/sitemap.xml'
    | '/dashboard/billing'
    | '/dashboard/keys'
    | '/dashboard/logs'
    | '/dashboard/settings'
    | '/docs/api-standards'
    | '/docs/cookbook'
    | '/docs/explorer'
    | '/docs/quick-start'
    | '/docs/sdks'
    | '/docs/security'
    | '/docs/webhooks'
    | '/ops/adapters'
    | '/ops/audit'
    | '/ops/integrators'
    | '/ops/keys'
    | '/ops/mdas'
    | '/ops/oversight'
    | '/ops/services'
    | '/ops/shifts'
    | '/ops/system'
    | '/signin/expired'
    | '/signin/sent'
    | '/work/assess'
    | '/work/history'
    | '/work/shift'
    | '/work/supervisor'
    | '/dashboard'
    | '/docs'
    | '/ops'
    | '/signin'
    | '/work'
    | '/docs/catalogue/agencies'
    | '/docs/catalogue/services'
    | '/work/collect/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/docs'
    | '/ops'
    | '/signin'
    | '/signup'
    | '/sitemap.xml'
    | '/work'
    | '/dashboard/billing'
    | '/dashboard/keys'
    | '/dashboard/logs'
    | '/dashboard/settings'
    | '/docs/api-standards'
    | '/docs/cookbook'
    | '/docs/explorer'
    | '/docs/quick-start'
    | '/docs/sdks'
    | '/docs/security'
    | '/docs/webhooks'
    | '/ops/adapters'
    | '/ops/audit'
    | '/ops/integrators'
    | '/ops/keys'
    | '/ops/mdas'
    | '/ops/oversight'
    | '/ops/services'
    | '/ops/shifts'
    | '/ops/system'
    | '/signin/expired'
    | '/signin/sent'
    | '/work/assess'
    | '/work/history'
    | '/work/shift'
    | '/work/supervisor'
    | '/dashboard/'
    | '/docs/'
    | '/ops/'
    | '/signin/'
    | '/work/'
    | '/docs/catalogue/agencies'
    | '/docs/catalogue/services'
    | '/work/collect/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  OpsRoute: typeof OpsRouteWithChildren
  SigninRoute: typeof SigninRouteWithChildren
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WorkRoute: typeof WorkRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof WorkRoute
    }
    '/signin/': {
      id: '/signin/'
      path: '/'
      fullPath: '/signin/'
      preLoaderRoute: typeof SigninIndexRouteImport
      parentRoute: typeof SigninRoute
    }
    '/ops/': {
      id: '/ops/'
      path: '/'
      fullPath: '/ops/'
      preLoaderRoute: typeof OpsIndexRouteImport
      parentRoute: typeof OpsRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/work/supervisor': {
      id: '/work/supervisor'
      path: '/supervisor'
      fullPath: '/work/supervisor'
      preLoaderRoute: typeof WorkSupervisorRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/shift': {
      id: '/work/shift'
      path: '/shift'
      fullPath: '/work/shift'
      preLoaderRoute: typeof WorkShiftRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/history': {
      id: '/work/history'
      path: '/history'
      fullPath: '/work/history'
      preLoaderRoute: typeof WorkHistoryRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/assess': {
      id: '/work/assess'
      path: '/assess'
      fullPath: '/work/assess'
      preLoaderRoute: typeof WorkAssessRouteImport
      parentRoute: typeof WorkRoute
    }
    '/signin/sent': {
      id: '/signin/sent'
      path: '/sent'
      fullPath: '/signin/sent'
      preLoaderRoute: typeof SigninSentRouteImport
      parentRoute: typeof SigninRoute
    }
    '/signin/expired': {
      id: '/signin/expired'
      path: '/expired'
      fullPath: '/signin/expired'
      preLoaderRoute: typeof SigninExpiredRouteImport
      parentRoute: typeof SigninRoute
    }
    '/ops/system': {
      id: '/ops/system'
      path: '/system'
      fullPath: '/ops/system'
      preLoaderRoute: typeof OpsSystemRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/shifts': {
      id: '/ops/shifts'
      path: '/shifts'
      fullPath: '/ops/shifts'
      preLoaderRoute: typeof OpsShiftsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/services': {
      id: '/ops/services'
      path: '/services'
      fullPath: '/ops/services'
      preLoaderRoute: typeof OpsServicesRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/oversight': {
      id: '/ops/oversight'
      path: '/oversight'
      fullPath: '/ops/oversight'
      preLoaderRoute: typeof OpsOversightRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/mdas': {
      id: '/ops/mdas'
      path: '/mdas'
      fullPath: '/ops/mdas'
      preLoaderRoute: typeof OpsMdasRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/keys': {
      id: '/ops/keys'
      path: '/keys'
      fullPath: '/ops/keys'
      preLoaderRoute: typeof OpsKeysRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/integrators': {
      id: '/ops/integrators'
      path: '/integrators'
      fullPath: '/ops/integrators'
      preLoaderRoute: typeof OpsIntegratorsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/audit': {
      id: '/ops/audit'
      path: '/audit'
      fullPath: '/ops/audit'
      preLoaderRoute: typeof OpsAuditRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/adapters': {
      id: '/ops/adapters'
      path: '/adapters'
      fullPath: '/ops/adapters'
      preLoaderRoute: typeof OpsAdaptersRouteImport
      parentRoute: typeof OpsRoute
    }
    '/docs/webhooks': {
      id: '/docs/webhooks'
      path: '/webhooks'
      fullPath: '/docs/webhooks'
      preLoaderRoute: typeof DocsWebhooksRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/security': {
      id: '/docs/security'
      path: '/security'
      fullPath: '/docs/security'
      preLoaderRoute: typeof DocsSecurityRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/sdks': {
      id: '/docs/sdks'
      path: '/sdks'
      fullPath: '/docs/sdks'
      preLoaderRoute: typeof DocsSdksRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/quick-start': {
      id: '/docs/quick-start'
      path: '/quick-start'
      fullPath: '/docs/quick-start'
      preLoaderRoute: typeof DocsQuickStartRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/explorer': {
      id: '/docs/explorer'
      path: '/explorer'
      fullPath: '/docs/explorer'
      preLoaderRoute: typeof DocsExplorerRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/cookbook': {
      id: '/docs/cookbook'
      path: '/cookbook'
      fullPath: '/docs/cookbook'
      preLoaderRoute: typeof DocsCookbookRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/api-standards': {
      id: '/docs/api-standards'
      path: '/api-standards'
      fullPath: '/docs/api-standards'
      preLoaderRoute: typeof DocsApiStandardsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/logs': {
      id: '/dashboard/logs'
      path: '/logs'
      fullPath: '/dashboard/logs'
      preLoaderRoute: typeof DashboardLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/keys': {
      id: '/dashboard/keys'
      path: '/keys'
      fullPath: '/dashboard/keys'
      preLoaderRoute: typeof DashboardKeysRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/work/collect/$id': {
      id: '/work/collect/$id'
      path: '/collect/$id'
      fullPath: '/work/collect/$id'
      preLoaderRoute: typeof WorkCollectIdRouteImport
      parentRoute: typeof WorkRoute
    }
    '/docs/catalogue/services': {
      id: '/docs/catalogue/services'
      path: '/catalogue/services'
      fullPath: '/docs/catalogue/services'
      preLoaderRoute: typeof DocsCatalogueServicesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/catalogue/agencies': {
      id: '/docs/catalogue/agencies'
      path: '/catalogue/agencies'
      fullPath: '/docs/catalogue/agencies'
      preLoaderRoute: typeof DocsCatalogueAgenciesRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardKeysRoute: typeof DashboardKeysRoute
  DashboardLogsRoute: typeof DashboardLogsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardKeysRoute: DashboardKeysRoute,
  DashboardLogsRoute: DashboardLogsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface DocsRouteChildren {
  DocsApiStandardsRoute: typeof DocsApiStandardsRoute
  DocsCookbookRoute: typeof DocsCookbookRoute
  DocsExplorerRoute: typeof DocsExplorerRoute
  DocsQuickStartRoute: typeof DocsQuickStartRoute
  DocsSdksRoute: typeof DocsSdksRoute
  DocsSecurityRoute: typeof DocsSecurityRoute
  DocsWebhooksRoute: typeof DocsWebhooksRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsCatalogueAgenciesRoute: typeof DocsCatalogueAgenciesRoute
  DocsCatalogueServicesRoute: typeof DocsCatalogueServicesRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsApiStandardsRoute: DocsApiStandardsRoute,
  DocsCookbookRoute: DocsCookbookRoute,
  DocsExplorerRoute: DocsExplorerRoute,
  DocsQuickStartRoute: DocsQuickStartRoute,
  DocsSdksRoute: DocsSdksRoute,
  DocsSecurityRoute: DocsSecurityRoute,
  DocsWebhooksRoute: DocsWebhooksRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsCatalogueAgenciesRoute: DocsCatalogueAgenciesRoute,
  DocsCatalogueServicesRoute: DocsCatalogueServicesRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface OpsRouteChildren {
  OpsAdaptersRoute: typeof OpsAdaptersRoute
  OpsAuditRoute: typeof OpsAuditRoute
  OpsIntegratorsRoute: typeof OpsIntegratorsRoute
  OpsKeysRoute: typeof OpsKeysRoute
  OpsMdasRoute: typeof OpsMdasRoute
  OpsOversightRoute: typeof OpsOversightRoute
  OpsServicesRoute: typeof OpsServicesRoute
  OpsShiftsRoute: typeof OpsShiftsRoute
  OpsSystemRoute: typeof OpsSystemRoute
  OpsIndexRoute: typeof OpsIndexRoute
}

const OpsRouteChildren: OpsRouteChildren = {
  OpsAdaptersRoute: OpsAdaptersRoute,
  OpsAuditRoute: OpsAuditRoute,
  OpsIntegratorsRoute: OpsIntegratorsRoute,
  OpsKeysRoute: OpsKeysRoute,
  OpsMdasRoute: OpsMdasRoute,
  OpsOversightRoute: OpsOversightRoute,
  OpsServicesRoute: OpsServicesRoute,
  OpsShiftsRoute: OpsShiftsRoute,
  OpsSystemRoute: OpsSystemRoute,
  OpsIndexRoute: OpsIndexRoute,
}

const OpsRouteWithChildren = OpsRoute._addFileChildren(OpsRouteChildren)

interface SigninRouteChildren {
  SigninExpiredRoute: typeof SigninExpiredRoute
  SigninSentRoute: typeof SigninSentRoute
  SigninIndexRoute: typeof SigninIndexRoute
}

const SigninRouteChildren: SigninRouteChildren = {
  SigninExpiredRoute: SigninExpiredRoute,
  SigninSentRoute: SigninSentRoute,
  SigninIndexRoute: SigninIndexRoute,
}

const SigninRouteWithChildren =
  SigninRoute._addFileChildren(SigninRouteChildren)

interface WorkRouteChildren {
  WorkAssessRoute: typeof WorkAssessRoute
  WorkHistoryRoute: typeof WorkHistoryRoute
  WorkShiftRoute: typeof WorkShiftRoute
  WorkSupervisorRoute: typeof WorkSupervisorRoute
  WorkIndexRoute: typeof WorkIndexRoute
  WorkCollectIdRoute: typeof WorkCollectIdRoute
}

const WorkRouteChildren: WorkRouteChildren = {
  WorkAssessRoute: WorkAssessRoute,
  WorkHistoryRoute: WorkHistoryRoute,
  WorkShiftRoute: WorkShiftRoute,
  WorkSupervisorRoute: WorkSupervisorRoute,
  WorkIndexRoute: WorkIndexRoute,
  WorkCollectIdRoute: WorkCollectIdRoute,
}

const WorkRouteWithChildren = WorkRoute._addFileChildren(WorkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  OpsRoute: OpsRouteWithChildren,
  SigninRoute: SigninRouteWithChildren,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WorkRoute: WorkRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
